<a href="https://colab.research.google.com/github/crsah234/anyangUniverSity_Third_second/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
[2주차] pandas DataFrame, indexing, filtering, dtype
"""
import pandas as pd
import numpy as np

In [5]:

# 실습용 무역 데이터 생성
np.random.seed(42)
# seed(42)가 있으면 다른 사람이 똑같은 코드를 실행해도 같은 랜덤 결과를 얻을 수 있어.

df = pd.DataFrame({
    "country": ["Korea", "Japan", "China", "USA", "Germany"] * 3,
    "year": np.repeat([2022, 2023, 2024], 5),
    "export": np.random.randint(100, 1000, 15).astype(float),
    "import_": np.random.randint(100, 1000, 15).astype(float),
    "region": (["Asia", "Asia", "Asia", "America", "Europe"] * 3),
})

In [6]:
df.head()
# df.tail()
# df.info()

   country  year  export  import_   region
0    Korea  2022   202.0    472.0     Asia
1    Japan  2022   535.0    199.0     Asia
2    China  2022   960.0    971.0     Asia
3      USA  2022   370.0    763.0  America
4  Germany  2022   206.0    230.0   Europe

In [7]:

# ------------------------------------------------------------
# 1. 데이터 구조 파악: 분석의 첫 습관
# ------------------------------------------------------------
print(df.head()) # 앞 5개
print("\nshape:", df.shape)
print("\ndtypes:\n", df.dtypes)
print("\ninfo:"); df.info()

   country  year  export  import_   region
0    Korea  2022   202.0    472.0     Asia
1    Japan  2022   535.0    199.0     Asia
2    China  2022   960.0    971.0     Asia
3      USA  2022   370.0    763.0  America
4  Germany  2022   206.0    230.0   Europe

shape: (15, 5)

dtypes:
 country     object
year         int64
export     float64
import_    float64
region      object
dtype: object

info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  15 non-null     object
 1   year     15 non-null     int64
 2   export   15 non-null     float64
 3   import_  15 non-null     float64
 4   region   15 non-null     object
dtypes: float64(2), int64(1), object(2)
memory usage: 732.0+ bytes

In [11]:
# ------------------------------------------------------------
# 2. Indexing: loc(라벨) vs iloc(위치)
# ------------------------------------------------------------
print("\nloc  예시:\n", df.loc[0:2, ["country", "export"]])
print("\niloc 예시:\n", df.iloc[0:4, 0:4])

loc  예시:
   country  export
0   Korea   202.0
1   Japan   535.0
2   China   960.0

iloc 예시:
   country  year  export  import_
0   Korea  2022   202.0    472.0
1   Japan  2022   535.0    199.0
2   China  2022   960.0    971.0
3     USA  2022   370.0    763.0

In [15]:
df['year']
# df["export"]

0     2022
1     2022
2     2022
3     2022
4     2022
5     2023
6     2023
7     2023
8     2023
9     2023
10    2024
11    2024
12    2024
13    2024
14    2024
Name: year, dtype: int64

In [16]:
# ------------------------------------------------------------
# 3. Filtering (Boolean indexing)
# ------------------------------------------------------------
cond = (df["year"] == 2024) & (df["export"] > 400)
print("\n2024년 수출 400 초과:\n", df[cond])

# query() 방식도 함께
print("\nquery 방식:\n", df.query("year == 2024 and export > 400"))

2024년 수출 400 초과:
    country  year  export  import_   region
10   Korea  2024   566.0    513.0     Asia
12   China  2024   430.0    485.0     Asia
13     USA  2024   558.0    291.0  America

query 방식:
    country  year  export  import_   region
10   Korea  2024   566.0    513.0     Asia
12   China  2024   430.0    485.0     Asia
13     USA  2024   558.0    291.0  America

In [17]:
print("\n cond 결과값 \n", cond)

 cond 결과값
 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12     True
13     True
14    False
dtype: bool

In [22]:
# ------------------------------------------------------------
# 4. 파생변수 생성과 dtype 관리
# ------------------------------------------------------------
print("변경전 \n", df.dtypes)
df["trade_balance"] = df["export"] - df["import_"]
df["region"] = df["region"].astype("category")   # 메모리 절약 + 범주형 명시
df["year"] = df["year"].astype("int16")
print("\ndtype 변경 후:\n", df.dtypes)

변경전
 country            object
year                int16
export            float64
import_           float64
region           category
trade_balance     float64
dtype: object

dtype 변경 후:
 country            object
year                int16
export            float64
import_           float64
region           category
trade_balance     float64
dtype: object

In [23]:
# ------------------------------------------------------------
# 5. groupby 기초
# ------------------------------------------------------------
print("\n국가별 평균 수출:\n", df.groupby("country", observed=True)["export"].mean())
print("\n지역-연도별 수출 합계:\n",
      df.groupby(["region", "year"])["export"].sum())

국가별 평균 수출:
 country
China      503.333333
Germany    204.666667
Japan      549.666667
Korea      313.000000
USA        547.333333
Name: export, dtype: float64

지역-연도별 수출 합계:
 region   year
America  2022     370.0
         2023     714.0
         2024     558.0
Asia     2022    1697.0
         2023    1091.0
         2024    1310.0
Europe   2022     206.0
         2023     221.0
         2024     187.0
Name: export, dtype: float64

/tmp/ipykernel_798/84579913.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["region", "year"])["export"].sum())

In [24]:
df.groupby(["region"], observed=True)["export"].mean()

region
America    547.333333
Asia       455.333333
Europe     204.666667
Name: export, dtype: float64

In [26]:
df_1=pd.read_csv('/content/drive/MyDrive/안양대학교_데이터처리실무(3학년2학기)/Accident_Disability_Train_all.csv')
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005 entries, 0 to 1004
Columns: 255 entries, UNIQUE_NO to ACNT_HSCLP_CTZ_DG_YR1
dtypes: float64(38), int64(214), object(3)
memory usage: 2.0+ MB

In [27]:
print(df_1["ACNT_HSCLP_CTZ_DG_YR1"].iloc[1])
print(df_1["ACNT_HSCLP_CTZ_DG_YR1"].iloc[1:5])
print(df_1.iloc[5:10])

# print("2번째행 출력: \n", df_1["Age_Grp"].iloc[1])
# print("\n 2번째행에서 6번째행까지 출력: \n",df_1["Age_Grp"].iloc[1:5])
# print("\n 6번째행~11번째행까지 출력: \n",df_1.iloc[5:10])

0.0
1    0.00000
2    0.26178
3    0.72464
4    0.00000
Name: ACNT_HSCLP_CTZ_DG_YR1, dtype: float64
   UNIQUE_NO  NH_TARGET  TOT_HSPZ_DYS  SM_DSAS_ACNT_YR1  \
5          6          1            71                 0
6          7          1             0                 6
7          8          1             0                 8
8          9          1             0                 6
9         10          1             0                 0

   PSG_DYS_CNTR_RIST_ACDDY  TOT_ISAMT  HSPZ_CNT_YR1  BILG_ISAMT  \
5                     3348   13320000             0    12000000
6                      353    8000000             0     7500000
7                     1513   15000000            10    15000000
8                     1981   22000000             3     8000000
9                      207   10000000             0    10000000

   SCRT_CNTR_CNT_MT3  CNTR_CNT_YR1  ...  SARG_NPCNT_YR1  SARG_INPCNT_YR1  \
5                  0             0  ...             230               25
6                  0             1  ...             193               24
7                  0             0  ...             119                5
8                  0             0  ...             339               15
9                  0             0  ...               0                0

   SARG_ACCNT_CMPR_NPCNT_RT_YR1  SAJG_ACCNT_YR1  SAJG_IVCNT_YR1  \
5                       9.96534             228               9
6                      17.54545               0               0
7                      12.68657               0               0
8                       9.65812               0               0
9                       0.00000               0               0

  SAJG_NPCNT_YR1  SAJG_INPCNT_YR1  HSCLP_ACNT_YR1  ACNT_CLPHS_CTZ_DG_YR1  \
5             21                5               0                0.00000
6              0                0               9                3.18021
7              0                0               5               33.33333
8              0                0               0                0.00000
9              0                0               0                0.00000

   ACNT_HSCLP_CTZ_DG_YR1
5                0.00000
6                0.55624
7                5.10204
8                0.00000
9                0.00000

[5 rows x 255 columns]

In [28]:
df_1.describe()
# print(df_1.describe(include="all"))
# print(df_1.describe(exclude=["O"])) # to exclude non-numerical values

,UNIQUE_NO,NH_TARGET,TOT_HSPZ_DYS,SM_DSAS_ACNT_YR1,PSG_DYS_CNTR_RIST_ACDDY,TOT_ISAMT,HSPZ_CNT_YR1,BILG_ISAMT,SCRT_CNTR_CNT_MT3,CNTR_CNT_YR1,...,SARG_NPCNT_YR1,SARG_INPCNT_YR1,SARG_ACCNT_CMPR_NPCNT_RT_YR1,SAJG_ACCNT_YR1,SAJG_IVCNT_YR1,SAJG_NPCNT_YR1,SAJG_INPCNT_YR1,HSCLP_ACNT_YR1,ACNT_CLPHS_CTZ_DG_YR1,ACNT_HSCLP_CTZ_DG_YR1
count,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1.005000e+03,1005.000000,1.005000e+03,1005.0,1005.000000,...,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000
mean,503.000000,0.573134,7.381095,4.514428,1995.799005,1.841947e+07,2.205970,1.152394e+07,0.0,0.641791,...,572.343284,92.720398,13.525352,4167.523383,99.980100,385.659701,36.590050,4.968159,7.168893,1.014382
std,290.262812,0.494869,30.465333,6.589035,2410.531733,2.361663e+07,2.857221,1.372702e+07,0.0,0.517661,...,491.754545,82.076138,7.221121,8603.403158,199.040731,750.039045,72.561549,12.395981,15.444263,3.240335
min,1.000000,0.000000,0.000000,0.000000,-124.000000,5.000000e+05,0.000000,4.000000e+05,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,252.000000,0.000000,0.000000,0.000000,131.000000,5.000000e+06,0.000000,3.000000e+06,0.0,0.000000,...,96.000000,8.000000,9.965340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,503.000000,1.000000,0.000000,3.000000,307.000000,1.198327e+07,2.000000,7.500000e+06,0.0,1.000000,...,502.000000,86.000000,14.921670,0.000000,0.000000,0.000000,0.000000,1.000000,0.666670,0.057810
75%,754.000000,1.000000,0.000000,6.000000,4250.000000,2.250000e+07,3.000000,1.500000e+07,0.0,1.000000,...,1004.000000,167.000000,19.435870,3640.000000,59.000000,367.000000,24.000000,5.000000,7.017540,0.609760
max,1005.000000,1.000000,403.000000,66.000000,7979.000000,2.072000e+08,22.000000,1.200000e+08,0.0,2.000000,...,1613.000000,258.000000,24.919240,37791.000000,729.000000,3091.000000,269.000000,179.000000,100.000000,50.000000

In [31]:
df_1.isnull()

,UNIQUE_NO,NH_TARGET,TOT_HSPZ_DYS,SM_DSAS_ACNT_YR1,PSG_DYS_CNTR_RIST_ACDDY,TOT_ISAMT,HSPZ_CNT_YR1,BILG_ISAMT,SCRT_CNTR_CNT_MT3,CNTR_CNT_YR1,...,SARG_NPCNT_YR1,SARG_INPCNT_YR1,SARG_ACCNT_CMPR_NPCNT_RT_YR1,SAJG_ACCNT_YR1,SAJG_IVCNT_YR1,SAJG_NPCNT_YR1,SAJG_INPCNT_YR1,HSCLP_ACNT_YR1,ACNT_CLPHS_CTZ_DG_YR1,ACNT_HSCLP_CTZ_DG_YR1
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1001,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1002,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1003,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1004,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [32]:
df_1.isnull().sum()

UNIQUE_NO                  0
NH_TARGET                  0
TOT_HSPZ_DYS               0
SM_DSAS_ACNT_YR1           0
PSG_DYS_CNTR_RIST_ACDDY    0
                          ..
SAJG_NPCNT_YR1             0
SAJG_INPCNT_YR1            0
HSCLP_ACNT_YR1             0
ACNT_CLPHS_CTZ_DG_YR1      0
ACNT_HSCLP_CTZ_DG_YR1      0
Length: 255, dtype: int64

In [33]:
# url 에서 직접 불러오기

# pd.read_csv("https://github.com/datadigger01/datamining/blob/main/DATA/SeoulBikeData.csv")
df_2 = pd.read_csv("https://raw.githubusercontent.com/datadigger01/datamining/main/DATA/SeoulBikeData.csv", encoding='cp949')
df_2

,Date,Rented Bike Count,Hour,Temperature(캜),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(캜),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,1003,19,4.2,34,2.6,1894,-10.3,0.0,0.0,0.0,Autumn,No Holiday,Yes
8756,30/11/2018,764,20,3.4,37,2.3,2000,-9.9,0.0,0.0,0.0,Autumn,No Holiday,Yes
8757,30/11/2018,694,21,2.6,39,0.3,1968,-9.9,0.0,0.0,0.0,Autumn,No Holiday,Yes
8758,30/11/2018,712,22,2.1,41,1.0,1859,-9.8,0.0,0.0,0.0,Autumn,No Holiday,Yes
8759,30/11/2018,584,23,1.9,43,1.3,1909,-9.3,0.0,0.0,0.0,Autumn,No Holiday,Yes

In [36]:
df_2.info()
df_2.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      8760 non-null   object
 1   Rented Bike Count         8760 non-null   int64
 2   Hour                      8760 non-null   int64
 3   Temperature(캜)            8760 non-null   float64
 4   Humidity(%)               8760 non-null   int64
 5   Wind speed (m/s)          8760 non-null   float64
 6   Visibility (10m)          8760 non-null   int64
 7   Dew point temperature(캜)  8760 non-null   float64
 8   Solar Radiation (MJ/m2)   8760 non-null   float64
 9   Rainfall(mm)              8760 non-null   float64
 10  Snowfall (cm)             8760 non-null   float64
 11  Seasons                   8760 non-null   object
 12  Holiday                   8760 non-null   object
 13  Functioning Day           8760 non-null   object
dtypes: float64(6), int64(4), object(4)
memory usage: 958.3+ KB

Date                         object
Rented Bike Count             int64
Hour                          int64
Temperature(캜)              float64
Humidity(%)                   int64
Wind speed (m/s)            float64
Visibility (10m)              int64
Dew point temperature(캜)    float64
Solar Radiation (MJ/m2)     float64
Rainfall(mm)                float64
Snowfall (cm)               float64
Seasons                      object
Holiday                      object
Functioning Day              object
dtype: object

In [ ]:
# 실습 TASK
# 1. 컬럼명을 적절하게 변환(AI활용)
# 2. Date 컬럼 타입을 object에서 date 타입으로 변환(AI활용)
# 3. Rented_Bike_Count 컬럼을 시계열데이터로해서 date 즉 time별로 그래프 그리기

### 1. 컬럼명 변환 (Column Renaming)

데이터프레임의 컬럼명을 분석하기 쉽고 명확한 영어 이름으로 변경합니다. 특수문자를 제거하고, 단위 정보를 포함하여 컬럼의 의미를 명확히 합니다.

In [ ]:
df_2.columns = [
    'Date',
    'Rented_Bike_Count',
    'Hour',
    'Temperature_C',
    'Humidity_percent',
    'Wind_speed_ms',
    'Visibility_10m',
    'Dew_point_temperature_C',
    'Solar_Radiation_MJ_m2',
    'Rainfall_mm',
    'Snowfall_cm',
    'Seasons',
    'Holiday',
    'Functioning_Day'
]
df_2.info()

### 2. 'Date' 컬럼 타입 변환 및 시간 데이터 생성

'Date' 컬럼을 `object` 타입에서 `datetime` 타입으로 변환하고, 'Date'와 'Hour' 컬럼을 합쳐서 완벽한 시계열 데이터를 위한 `datetime` 인덱스를 생성합니다. `errors='coerce'`를 사용하여 변환할 수 없는 값은 `NaT` (Not a Time)로 처리합니다.

In [37]:
df_2['Date'] = pd.to_datetime(df_2['Date'], format='%d/%m/%Y', errors='coerce')
# 'Date'와 'Hour'를 결합하여 완전한 datetime 객체 생성
df_2['Datetime'] = df_2['Date'] + pd.to_timedelta(df_2['Hour'], unit='h')
df_2.set_index('Datetime', inplace=True)
df_2.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8760 entries, 2017-12-01 00:00:00 to 2018-11-30 23:00:00
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      8760 non-null   datetime64[ns]
 1   Rented Bike Count         8760 non-null   int64
 2   Hour                      8760 non-null   int64
 3   Temperature(캜)            8760 non-null   float64
 4   Humidity(%)               8760 non-null   int64
 5   Wind speed (m/s)          8760 non-null   float64
 6   Visibility (10m)          8760 non-null   int64
 7   Dew point temperature(캜)  8760 non-null   float64
 8   Solar Radiation (MJ/m2)   8760 non-null   float64
 9   Rainfall(mm)              8760 non-null   float64
 10  Snowfall (cm)             8760 non-null   float64
 11  Seasons                   8760 non-null   object
 12  Holiday                   8760 non-null   object
 13  Functioning Day           8760 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(4), object(3)
memory usage: 1.0+ MB

### 3. 'Rented_Bike_Count' 시계열 그래프 그리기

이제 'Rented_Bike_Count' 컬럼을 시계열 데이터로 사용하여 시간에 따른 자전거 대여량 변화를 그래프로 시각화합니다. 이를 통해 시간별, 일별, 계절별 패턴을 파악할 수 있습니다.

In [38]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.lineplot(data=df_2, x=df_2.index, y='Rented_Bike_Count')
plt.title('Rented Bike Count Over Time')
plt.xlabel('Date and Time')
plt.ylabel('Rented Bike Count')
plt.grid(True)
plt.tight_layout()
plt.show()

ValueError: Could not interpret value `Rented_Bike_Count` for `y`. An entry with this name does not appear in `data`.