<a href="https://colab.research.google.com/github/crsah234/anyangUniverSity_Third_second/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
[2주차] pandas DataFrame, indexing, filtering, dtype
"""
import pandas as pd
import numpy as np

# 실습용 무역 데이터 생성
np.random.seed(42)
df = pd.DataFrame({
    "country": ["Korea", "Japan", "China", "USA", "Germany"] * 3,
    "year": np.repeat([2022, 2023, 2024], 5),
    "export": np.random.randint(100, 1000, 15).astype(float),
    "import_": np.random.randint(100, 1000, 15).astype(float),
    "region": (["Asia", "Asia", "Asia", "America", "Europe"] * 3),
})

In [ ]:
df.head()
# df.tail()
# df.info()

   country  year  export  import_   region
0    Korea  2022   202.0    472.0     Asia
1    Japan  2022   535.0    199.0     Asia
2    China  2022   960.0    971.0     Asia
3      USA  2022   370.0    763.0  America
4  Germany  2022   206.0    230.0   Europe

In [ ]:
# ------------------------------------------------------------
# 1. 데이터 구조 파악: 분석의 첫 습관
# ------------------------------------------------------------
print(df.head())
print("\nshape:", df.shape)
print("\ndtypes:\n", df.dtypes)
print("\ninfo:"); df.info()

   country  year  export  import_   region
0    Korea  2022   202.0    472.0     Asia
1    Japan  2022   535.0    199.0     Asia
2    China  2022   960.0    971.0     Asia
3      USA  2022   370.0    763.0  America
4  Germany  2022   206.0    230.0   Europe

shape: (15, 5)

dtypes:
 country     object
year         int64
export     float64
import_    float64
region      object
dtype: object

info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  15 non-null     object
 1   year     15 non-null     int64
 2   export   15 non-null     float64
 3   import_  15 non-null     float64
 4   region   15 non-null     object
dtypes: float64(2), int64(1), object(2)
memory usage: 732.0+ bytes

In [ ]:
# ------------------------------------------------------------
# 2. Indexing: loc(라벨) vs iloc(위치)
# ------------------------------------------------------------
print("\nloc  예시:\n", df.loc[0:2, ["country", "export"]])
print("\niloc 예시:\n", df.iloc[0:3, 0:3])

loc  예시:
   country  export
0   Korea   202.0
1   Japan   535.0
2   China   960.0

iloc 예시:
   country  year  export
0   Korea  2022   202.0
1   Japan  2022   535.0
2   China  2022   960.0

In [ ]:
df['year']
df["export"]

0     202.0
1     535.0
2     960.0
3     370.0
4     206.0
5     171.0
6     800.0
7     120.0
8     714.0
9     221.0
10    566.0
11    314.0
12    430.0
13    558.0
14    187.0
Name: export, dtype: float64

In [ ]:
# ------------------------------------------------------------
# 3. Filtering (Boolean indexing)
# ------------------------------------------------------------
cond = (df["year"] == 2024) & (df["export"] > 400)
print("\n2024년 수출 400 초과:\n", df[cond])

# query() 방식도 함께
print("\nquery 방식:\n", df.query("year == 2024 and export > 400"))

2024년 수출 400 초과:
    country  year  export  import_   region
10   Korea  2024   566.0    513.0     Asia
12   China  2024   430.0    485.0     Asia
13     USA  2024   558.0    291.0  America

query 방식:
    country  year  export  import_   region
10   Korea  2024   566.0    513.0     Asia
12   China  2024   430.0    485.0     Asia
13     USA  2024   558.0    291.0  America

In [ ]:

print("\n cond 결과값 \n", cond)

 cond 결과값
 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12     True
13     True
14    False
dtype: bool

In [ ]:
# ------------------------------------------------------------
# 4. 파생변수 생성과 dtype 관리
# ------------------------------------------------------------
df["trade_balance"] = df["export"] - df["import_"]
df["region"] = df["region"].astype("category")   # 메모리 절약 + 범주형 명시
# dataframe.astype : 데이터프레임의 데이터 타입(dtype)을 지정한 다른 타입으로 변경할 때 사용
df["year"] = df["year"].astype("int16")
print("\ndtype 변경 후:\n", df.dtypes)

dtype 변경 후:
 country            object
year                int16
export            float64
import_           float64
region           category
trade_balance     float64
dtype: object

In [ ]:
# ------------------------------------------------------------
# 5. groupby 기초
# ------------------------------------------------------------
print("\n국가별 평균 수출:\n", df.groupby("country", observed=True)["export"].mean())
print("\n지역-연도별 수출 합계:\n",
      df.groupby(["region", "year"])["export"].sum())

국가별 평균 수출:
 country
China      503.333333
Germany    204.666667
Japan      549.666667
Korea      313.000000
USA        547.333333
Name: export, dtype: float64

지역-연도별 수출 합계:
 region   year
America  2022     370.0
         2023     714.0
         2024     558.0
Asia     2022    1697.0
         2023    1091.0
         2024    1310.0
Europe   2022     206.0
         2023     221.0
         2024     187.0
Name: export, dtype: float64

/tmp/ipykernel_986/84579913.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["region", "year"])["export"].sum())

In [ ]:
# df.groupby(["region"], observed=True)["export"].mean()

In [ ]:
url = "https://raw.githubusercontent.com/datadigger01/datamining/main/DATA/SeoulBikeData.csv"
df_1= pd.read_csv(url, encoding="cp949")
df_1

,Date,Rented Bike Count,Hour,Temperature(캜),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(캜),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,1003,19,4.2,34,2.6,1894,-10.3,0.0,0.0,0.0,Autumn,No Holiday,Yes
8756,30/11/2018,764,20,3.4,37,2.3,2000,-9.9,0.0,0.0,0.0,Autumn,No Holiday,Yes
8757,30/11/2018,694,21,2.6,39,0.3,1968,-9.9,0.0,0.0,0.0,Autumn,No Holiday,Yes
8758,30/11/2018,712,22,2.1,41,1.0,1859,-9.8,0.0,0.0,0.0,Autumn,No Holiday,Yes
8759,30/11/2018,584,23,1.9,43,1.3,1909,-9.3,0.0,0.0,0.0,Autumn,No Holiday,Yes

In [ ]:
# 데이터파일 읽어오기

In [ ]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      8760 non-null   object
 1   Rented Bike Count         8760 non-null   int64
 2   Hour                      8760 non-null   int64
 3   Temperature(캜)            8760 non-null   float64
 4   Humidity(%)               8760 non-null   int64
 5   Wind speed (m/s)          8760 non-null   float64
 6   Visibility (10m)          8760 non-null   int64
 7   Dew point temperature(캜)  8760 non-null   float64
 8   Solar Radiation (MJ/m2)   8760 non-null   float64
 9   Rainfall(mm)              8760 non-null   float64
 10  Snowfall (cm)             8760 non-null   float64
 11  Seasons                   8760 non-null   object
 12  Holiday                   8760 non-null   object
 13  Functioning Day           8760 non-null   object
dtypes: float64(6), int64(4), object(4)
memory usage: 958.3+ KB

In [ ]:
print(df_1["Age_Grp"].iloc[1])
print(df_1["Age_Grp"].iloc[1:5])
print(df_1.iloc[5:10])

# print("2번째행 출력: \n", df_1["Age_Grp"].iloc[1])
# print("\n 2번째행에서 6번째행까지 출력: \n",df_1["Age_Grp"].iloc[1:5])
# print("\n 6번째행~11번째행까지 출력: \n",df_1.iloc[5:10])

KeyError: 'Age_Grp'

In [ ]:

df_1.describe()
# print(df_1.describe(include="all"))
# print(df_1.describe(exclude=["O"])) # to exclude non-numerical values

,TOTAL_VALUE,princ_1,princ_2,LOT_SQFT,GROSS_AREA,LIVING_AREA,FLOORS,ROOMS,BEDROOMS,FULL_BATH,HALF_BATH,KITCHEN,FIREPLACE,YR_BUILT_CAT_0,YR_BUILT_CAT_1,YR_BUILT_CAT_2,REMODEL_Unknown,REMODEL_Recent,REMODEL_Old
count,5802.000000,5.802000e+03,5.802000e+03,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.00000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000
mean,392.685715,-5.878327e-17,4.898606e-18,6278.083764,2924.842123,1657.065322,1.683730,6.994829,3.230093,1.296794,0.613926,1.01534,0.739917,0.078594,0.797484,0.123923,0.749052,0.150810,0.100138
std,99.177414,1.488369e+00,8.278959e-01,2669.707974,883.984726,540.456726,0.444884,1.437657,0.846607,0.522040,0.533839,0.12291,0.565108,0.269127,0.401910,0.329522,0.433596,0.357894,0.300210
min,105.000000,-3.386174e+00,-4.057055e+00,997.000000,821.000000,504.000000,1.000000,3.000000,1.000000,1.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,325.125000,-9.523190e-01,-4.372519e-01,4772.000000,2347.000000,1308.000000,1.000000,6.000000,3.000000,1.000000,0.000000,1.00000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,375.900000,-3.534898e-01,-7.616576e-02,5683.000000,2700.000000,1548.500000,2.000000,7.000000,3.000000,1.000000,1.000000,1.00000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
75%,438.775000,5.157168e-01,3.304379e-01,7022.250000,3239.000000,1873.750000,2.000000,8.000000,4.000000,2.000000,1.000000,1.00000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
max,1217.800000,1.260624e+01,1.045376e+01,46411.000000,8154.000000,5289.000000,3.000000,14.000000,9.000000,5.000000,3.000000,2.00000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df_1.isnull()
# df_1.isnull().sum()

,TOTAL_VALUE,princ_1,princ_2,LOT_SQFT,GROSS_AREA,LIVING_AREA,FLOORS,ROOMS,BEDROOMS,FULL_BATH,HALF_BATH,KITCHEN,FIREPLACE,YR_BUILT_CAT_0,YR_BUILT_CAT_1,YR_BUILT_CAT_2,REMODEL_Unknown,REMODEL_Recent,REMODEL_Old
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5797,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5798,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5799,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5800,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5801,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#url 에서 직접 불러오기

# pd.read_csv("https://github.com/datadigger01/datamining/blob/main/DATA/SeoulBikeData.csv")
df_2 = pd.read_csv("https://raw.githubusercontent.com/datadigger01/datamining/main/DATA/SeoulBikeData.csv", encoding='cp949')
df_2

,Date,Rented Bike Count,Hour,Temperature(캜),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(캜),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,1003,19,4.2,34,2.6,1894,-10.3,0.0,0.0,0.0,Autumn,No Holiday,Yes
8756,30/11/2018,764,20,3.4,37,2.3,2000,-9.9,0.0,0.0,0.0,Autumn,No Holiday,Yes
8757,30/11/2018,694,21,2.6,39,0.3,1968,-9.9,0.0,0.0,0.0,Autumn,No Holiday,Yes
8758,30/11/2018,712,22,2.1,41,1.0,1859,-9.8,0.0,0.0,0.0,Autumn,No Holiday,Yes
8759,30/11/2018,584,23,1.9,43,1.3,1909,-9.3,0.0,0.0,0.0,Autumn,No Holiday,Yes

In [ ]:
df_2.info()
df_2.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      8760 non-null   object
 1   Rented Bike Count         8760 non-null   int64
 2   Hour                      8760 non-null   int64
 3   Temperature(캜)            8760 non-null   float64
 4   Humidity(%)               8760 non-null   int64
 5   Wind speed (m/s)          8760 non-null   float64
 6   Visibility (10m)          8760 non-null   int64
 7   Dew point temperature(캜)  8760 non-null   float64
 8   Solar Radiation (MJ/m2)   8760 non-null   float64
 9   Rainfall(mm)              8760 non-null   float64
 10  Snowfall (cm)             8760 non-null   float64
 11  Seasons                   8760 non-null   object
 12  Holiday                   8760 non-null   object
 13  Functioning Day           8760 non-null   object
dtypes: float64(6), int64(4), object(4)
memory usage: 958.3+ KB

Date                         object
Rented Bike Count             int64
Hour                          int64
Temperature(캜)              float64
Humidity(%)                   int64
Wind speed (m/s)            float64
Visibility (10m)              int64
Dew point temperature(캜)    float64
Solar Radiation (MJ/m2)     float64
Rainfall(mm)                float64
Snowfall (cm)               float64
Seasons                      object
Holiday                      object
Functioning Day              object
dtype: object

In [ ]:
# 실습 TASK
# 1. 컬럼명을 적절하게 변환(AI활용)
# 2. Date 컬럼 타입을 object에서 date 타입으로 변환(AI활용)
# 3. Rented_Bike_Count 컬럼을 시계열데이터로해서 date 즉 time별로 그래프 그리기

### 1. 컬럼명 적절하게 변환

컬럼명에 특수문자나 한글이 포함되어 있어 파이썬에서 사용하기 편리하도록 영문으로 변경합니다.

In [ ]:
def clean_column_names(df):
    # Define a mapping for complex column names
    column_mapping = {
        'Rented Bike Count': 'Rented_Bike_Count',
        'Temperature(캜)': 'Temperature_C',
        'Humidity(%)': 'Humidity_perc',
        'Wind speed (m/s)': 'Wind_Speed_ms',
        'Visibility (10m)': 'Visibility_10m',
        'Dew point temperature(캜)': 'Dew_Point_Temperature_C',
        'Solar Radiation (MJ/m2)': 'Solar_Radiation_MJ_m2',
        'Rainfall(mm)': 'Rainfall_mm',
        'Snowfall (cm)': 'Snowfall_cm',
        'Functioning Day': 'Functioning_Day'
    }
    # Rename columns using the mapping
    df = df.rename(columns=column_mapping)

    # Further clean by removing extra spaces and special characters
    df.columns = df.columns.str.strip().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
    return df

df_1 = clean_column_names(df_1)

print("변경된 컬럼명:")
display(df_1.columns.tolist())

### 2. 'Date' 컬럼 타입을 `object`에서 `datetime` 타입으로 변환

`Date` 컬럼을 시계열 분석을 위해 `datetime` 형식으로 변환합니다.

In [ ]:
# 'Date' 컬럼을 datetime 타입으로 변환 (format에 맞게 조정)
# 원본 데이터의 날짜 형식: DD/MM/YYYY
df_1['Date'] = pd.to_datetime(df_1['Date'], format='%d/%m/%Y')

print("'Date' 컬럼 변환 후 정보:")
df_1.info()

### 3. `Rented_Bike_Count` 컬럼을 시계열 데이터로 시간별 그래프 그리기

날짜별 자전거 대여량 변화를 시각화하여 트렌드를 파악합니다.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# 시간별 총 자전거 대여량 계산
daily_rented_bike_count = df_1.groupby('Date')['Rented_Bike_Count'].sum().reset_index()

plt.figure(figsize=(15, 7))
sns.lineplot(x='Date', y='Rented_Bike_Count', data=daily_rented_bike_count)
plt.title('일별 자전거 대여량 변화 (Time Series)')
plt.xlabel('날짜')
plt.ylabel('총 대여 자전거 수')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()